### ISSUE TITLE
Visor panics when lotusrepo and indexhead are both enabled

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel-visor#162]
### Describe the bug:

```
Oct 28 16:46:41 graben visor[302709]: panic: runtime error: makeslice: len out of range
Oct 28 16:46:41 graben visor[302709]: goroutine 1 [running]:
Oct 28 16:46:41 graben visor[302709]: github.com/filecoin-project/sentinel-visor/tasks/indexer.NewTipSetCache(...)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/src/github.com/filecoin-project/sentinel-visor/tasks/indexer/tipset.go:24
Oct 28 16:46:41 graben visor[302709]: github.com/filecoin-project/sentinel-visor/tasks/indexer.NewChainHeadIndexer(...)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/src/github.com/filecoin-project/sentinel-visor/tasks/indexer/chainheadindexer.go:29
Oct 28 16:46:41 graben visor[302709]: github.com/filecoin-project/sentinel-visor/commands.glob..func3(0xc0004e6740, 0x0, 0x0)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/src/github.com/filecoin-project/sentinel-visor/commands/run.go:263 +0x229b
Oct 28 16:46:41 graben visor[302709]: github.com/urfave/cli/v2.(*Command).Run(0x5fad2e0, 0xc0003ed980, 0x0, 0x0)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
Oct 28 16:46:41 graben visor[302709]: github.com/urfave/cli/v2.(*App).RunContext(0xc0002dc000, 0x38a5900, 0xc000050160, 0xc00000c3c0, 0x1d, 0x1e, 0x0, 0x0)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
Oct 28 16:46:41 graben visor[302709]: github.com/urfave/cli/v2.(*App).Run(...)
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
Oct 28 16:46:41 graben visor[302709]: main.main()
Oct 28 16:46:41 graben visor[302709]:         /home/lanzafame/src/github.com/filecoin-project/sentinel-visor/main.go:115 +0xe30
```

### Steps to Reproduce:
Enable lotusrepo and indexhead at the same time.

**Comment by willscott** [comment]
on lotus repo we don't expect any new tipsets to ever appear. what are you hoping the `indexhead` would do in this scenario (besides not-crashing)

**Comment by frrist** [comment]
Disallowing them to both be enabled simultaneously seems like a reasonable solution.

**Comment by lanzafame** [comment]
Just not crashing. I had forgotten to remove the `indexhead` flag. I would expect that the `indexhead` flag is just ignored when running lotusrepo

**Comment by frrist** [comment]
This issue has rotted, closing.
