### ISSUE TITLE
Visor fails to close database connections cleanly

### ISSUE THREAD

**Issue by lanzafame** [filecoin-project/sentinel-visor#53]
```
^C2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing deal states: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:85	failed to process tipset	{"error": "process tipset: get actor: handler: websocket connection closed", "height": 110422}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing deal states: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:87	failed to mark tipset complete	{"error": "context canceled", "height": 110422}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	ERROR	message	message/message.go:87	failed to process tipset	{"error": "process tipset: fetch receipts: handler: websocket connection closed", "height": 108992}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: RPC client error: sendRequest failed: websocket routine exiting"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:85	failed to process tipset	{"error": "process tipset: get actor changes: handler: websocket connection closed", "height": 110420}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:85	failed to process tipset	{"error": "process tipset: get actor parent: handler: websocket connection closed", "height": 110427}
2020-10-02T18:00:47.528+1000	ERROR	message	message/message.go:89	failed to mark tipset messages complete	{"error": "context canceled", "height": 108992}
2020-10-02T18:00:47.528+1000	ERROR	message	message/message.go:87	failed to process tipset	{"error": "process tipset: fetch messages: handler: websocket connection closed", "height": 108974}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "MessageProcessor002"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateProcessor008"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:85	failed to process tipset	{"error": "process tipset: get actor parent: handler: websocket connection closed", "height": 110424}
2020-10-02T18:00:47.528+1000	ERROR	message	message/message.go:89	failed to mark tipset messages complete	{"error": "pg: database is closed", "height": 108974}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "pg: database is closed"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "MessageProcessor001"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "context canceled"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateProcessor010"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateProcessor009"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "extract actor state: diffing miner sectors: read obj: handler: websocket connection closed"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstate.go:163	failed to mark actor complete	{"error": "pg: database is closed"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateProcessor002"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:87	failed to mark tipset complete	{"error": "context canceled", "height": 110427}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateChangeProcessor003"}
2020-10-02T18:00:47.528+1000	ERROR	actorstate	actorstate/actorstatechange.go:87	failed to mark tipset complete	{"error": "context canceled", "height": 110420}
2020-10-02T18:00:47.529+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateChangeProcessor004"}
2020-10-02T18:00:47.529+1000	ERROR	message	message/message.go:87	failed to process tipset	{"error": "process tipset: persist: read tcp 192.168.1.11:43918->192.168.1.254:5432: use of closed network connection", "height": 109009}
2020-10-02T18:00:47.529+1000	ERROR	actorstate	actorstate/actorstate.go:158	process actor	{"error": "persisting raw state: read tcp 192.168.1.11:43936->192.168.1.254:5432: use of closed network connection"}
2020-10-02T18:00:47.528+1000	INFO	schedule	schedule/scheduler.go:122	task exited cleanly, restarting	{"task": "ActorStateProcessor012"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10b008a]

goroutine 235225 [running]:
go.opentelemetry.io/otel/sdk/trace.(*evictedQueue).add(...)
	/home/lanzafame/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/evictedqueue.go:33
go.opentelemetry.io/otel/sdk/trace.(*span).addEventWithTimestamp(0xc0b311b570, 0xbfd5d56bdf89148a, 0x1a3d9e695f, 0x432b160, 0x2349fa6, 0x5, 0xc08363cc80, 0x2, 0x2)
	/home/lanzafame/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:217 +0x14a
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc0b311b570, 0x0, 0x0, 0x0)
	/home/lanzafame/pkg/mod/go.opentelemetry.io/otel/sdk@v0.12.0/trace/span.go:126 +0x5c5
panic(0x21b02e0, 0x4296d80)
	/usr/lib/go/src/runtime/panic.go:969 +0x175
github.com/filecoin-project/sentinel-visor/storage.(*Database).MarkTipSetMessagesComplete(0xc0005ac100, 0x26153c0, 0xc0b08e68a0, 0xc07c615380, 0x7f, 0x1a9d1, 0xbfd5d56bdf8899a7, 0x1a3d9dee7c, 0x432b160, 0xc0b5c58540, ...)
	/home/lanzafame/src/github.com/filecoin-project/sentinel-visor/storage/sql.go:468 +0xf3
github.com/filecoin-project/sentinel-visor/tasks/message.(*MessageProcessor).processBatch(0xc000716f90, 0x26153c0, 0xc0b08e68a0, 0x0, 0x0, 0x0)
	/home/lanzafame/src/github.com/filecoin-project/sentinel-visor/tasks/message/message.go:88 +0x525
github.com/filecoin-project/sentinel-visor/tasks/message.(*MessageProcessor).Run(0xc000716f90, 0x2615340, 0xc0001e0400, 0xc, 0x0)
	/home/lanzafame/src/github.com/filecoin-project/sentinel-visor/tasks/message/message.go:51 +0x3f
github.com/filecoin-project/sentinel-visor/schedule.(*Scheduler).Run.func1(0xc0001eb620, 0xc000485550, 0xc0001dea20, 0x13, 0x25f3980, 0xc000716f90, 0x0, 0x0, 0x101)
	/home/lanzafame/src/github.com/filecoin-project/sentinel-visor/schedule/scheduler.go:105 +0x1c9
created by github.com/filecoin-project/sentinel-visor/schedule.(*Scheduler).Run
	/home/lanzafame/src/github.com/filecoin-project/sentinel-visor/schedule/scheduler.go:69 +0x22b
```

**Comment by iand** [comment]
Often connections are left open after visor has been shut down. This appears in the postgres logs:
```
2020-10-14 10:52:24.664 UTC [15859] LOG:  could not receive data from client: Connection reset by peer
2020-10-14 10:52:24.664 UTC [15859] LOG:  unexpected EOF on client connection with an open transaction
```
